### ISSUE TITLE
Creating JSON Index with sortable TagField throws exception

### ISSUE THREAD

**Issue by hbacharya** [redis/NRedisStack#175]
**NRedisStack Version**: 0.8.1

**Redis Stack Version**: Redis server v=6.2.12 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=4dbc2487343b0024

**Description**: 
Creating JSON index with **sortable** TagField throws exception.

Note: The problem only happens if the **sortable = true**.  (It works as expected when sortable = false)

Please check the sample below:

```cs
        static void Main(string[] args)
        {
            ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("localhost:6379");
            IDatabase db = redis.GetDatabase();

            SearchCommands ft = db.FT();
            JsonCommands json = db.JSON();

            var sortable = true;
            //Add a tag field with sortable = true
            var schema = new Schema().AddTagField("",sortable, false, false,"|");

            //following line throws exception (Note: sortable = true)
            ft.Create("myIndex", new FTCreateParams().On(IndexDataType.JSON)
                    .Prefix("doc:"), schema);
        }
```

**Exception:**

```cs
Unhandled exception. StackExchange.Redis.RedisServerException: Invalid field type for field `SEPARATOR`
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server, T defaultValue) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1992
   at StackExchange.Redis.RedisDatabase.Execute(String command, ICollection`1 args, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 1502
   at NRedisStack.SearchCommands.Create(String indexName, FTCreateParams parameters, Schema schema)
   at RedisSortTest.Program.Main(String[] args)
```

**Comment by haysch** [comment]
It seems like the field ordering of the FT.CREATE command is wrong.

By doing a quick test in `redis-cli` I note that:

```
127.0.0.1:6379> FT.CREATE idx ON HASH PREFIX 1 test: SCHEMA tags TAG SORTABLE SEPARATOR "|"
(error) Invalid field type for field `SEPARATOR`
127.0.0.1:6379> FT.CREATE idx ON HASH PREFIX 1 test: SCHEMA tags TAG SEPARATOR "|" SORTABLE
OK
127.0.0.1:6379> FT.DROP idx
OK
127.0.0.1:6379> FT.CREATE idx ON HASH PREFIX 1 test: SCHEMA tags TAG SEPARATOR "|" SORTABLE WITHSUFFIXTRIE
(error) Field `WITHSUFFIXTRIE` does not have a type
127.0.0.1:6379> FT.CREATE idx ON HASH PREFIX 1 test: SCHEMA tags TAG SEPARATOR "|" CASESENSITIVE WITHSUFFIXTRIE SORTABLE
OK
```

So the solution is to order the fields of FT.CREATE such that `SORTABLE` is the last field.
However, it is not completely clear from the Redis documentation on FT.CREATE.

**Comment by haysch** [comment]
I see the problem also exists for TEXT as well.
@shacharPash is it something that you will look into and fix?

**Comment by shacharPash** [comment]
fixed in #176

**Comment by hbacharya** [comment]
Great! You guys are amazing.

I will download once next version is released.

Thanks a lot.

**Comment by hbacharya** [comment]
Hello,

Any plan when are you planning to release?
